### ISSUE TITLE
org.lemsml.jlems.test.LemsExamplesReaderTest fails on display error

### ISSUE THREAD

**Issue by rgerkin** [NeuroML/jNeuroML#52]
OSX 10.12.6
`python getNeuroML.py development` fails with:  

`Tests run: 37, Failures: 0, Errors: 1, Skipped: 0`

stdout for the whole suite of tests is a bit hard to read (none of the `\n` or `\r` chars got correctly escaped in my terminal) but the error is in this test:  
```bash
Richards-iMac:jNeuroML rgerkin$ more /Users/rgerkin/neuroml/jlems/target/surefire-reports/org.lemsml.jlems.test.LemsExamplesReaderTest.txt 
-------------------------------------------------------------------------------
Test set: org.lemsml.jlems.test.LemsExamplesReaderTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.037 sec <<< FAILURE! - in org.lemsml.jlems.test.LemsExamplesReaderTest
testReadFromString(org.lemsml.jlems.test.LemsExamplesReaderTest)  Time elapsed: 0.036 sec  <<< ERROR!
org.lemsml.jlems.core.sim.ContentError: No display defined for recorder Recorder q=quantity, scale=scale, display=display, color=color
        at org.lemsml.jlems.core.type.simulation.Simulation.appendToBehavior(Simulation.java:100)
        at org.lemsml.jlems.core.type.ComponentType.makeStateType(ComponentType.java:991)
        at org.lemsml.jlems.core.type.Component.makeStateType(Component.java:759)
        at org.lemsml.jlems.core.type.Component.getStateType(Component.java:814)
        at org.lemsml.jlems.core.type.Component.getStateType(Component.java:793)
        at org.lemsml.jlems.core.type.ComponentType.makeStateType(ComponentType.java:970)
        at org.lemsml.jlems.core.type.Component.makeStateType(Component.java:759)
        at org.lemsml.jlems.core.type.Component.getStateType(Component.java:814)
        at org.lemsml.jlems.core.type.Component.getStateType(Component.java:793)
        at org.lemsml.jlems.core.type.ComponentType.makeStateType(ComponentType.java:970)
        at org.lemsml.jlems.core.type.Component.makeStateType(Component.java:759)
        at org.lemsml.jlems.core.type.Component.getStateType(Component.java:814)
        at org.lemsml.jlems.core.type.Component.getStateType(Component.java:793)
        at org.lemsml.jlems.core.type.ComponentType.makeStateType(ComponentType.java:970)
        at org.lemsml.jlems.core.type.Component.makeStateType(Component.java:759)
        at org.lemsml.jlems.core.type.Component.getStateType(Component.java:814)
        at org.lemsml.jlems.core.type.Component.getStateType(Component.java:793)
        at org.lemsml.jlems.core.sim.Sim.build(Sim.java:87)
        at org.lemsml.jlems.test.LemsExamplesReaderTest.testReadFromString(LemsExamplesReaderTest.java:82)
```

There is some display variable issue.  

I need to install this development version to get the changes you added a few weeks ago to allow include paths to be specified in the jnml command.

**Comment by pgleeson** [comment]
@rgerkin For errors like this when installing jNeuroML from source, I'd recommend going through each of jLEMS, org.neuroml.model, org.neuroml.export, org.neuroml.import, jNeuroML and 

- make sure it's on development branch
- pull the latest
- make sure 'mvn clean install' works

Though it seems it's just jLEMS you have the problem with, which is simplest in terms of dependencies. Current development branch is passing fine: https://travis-ci.org/LEMS/jLEMS/branches

**Comment by rgerkin** [comment]
@pgleeson OK, thanks, that fixed that problem.  Now how do I go about making this the jnml that ends up in `pyneuroml/lib/jNeuroML-X-jar-with-dependencies.jar` so I can use it from pyneuroml?

**Comment by pgleeson** [comment]
@rgerkin Best way for you to do that locally is just to copy the jar from jNeuroML/target/jNeuroML-0.8.3-jar-with-dependencies.jar to pyNeuroML/pyneuroml/lib/jNeuroML-0.8.3-jar-with-dependencies.jar and python setup.py install again.

I wanted to do a binary release with these, but have some more testing to complete before doing that. A week or so...

**Comment by rgerkin** [comment]
@pgleeson Thanks, everything works great now.
